version: '3.8'

services:
  created_teachers:
    image: gabrielrv/created_teachers:latest
    container_name: created_teachers
    restart: always
    ports:
      - "8010:8010"
    environment:
      - DB_HOST_TEACHER=${DB_HOST_TEACHER}
      - DB_PORT_TEACHER=${DB_PORT_TEACHER}
      - DB_USER_TEACHER=${DB_USER_TEACHER}
      - DB_PASSWORD_TEACHER=${DB_PASSWORD_TEACHER}
      - DB_NAME_TEACHER=${DB_NAME_TEACHER}

  delete_teachers:
    image: gabrielrv/delete_teachers:latest
    container_name: delete_teachers
    restart: always
    ports:
      - "8013:8013"
    environment:
      - DB_HOST_TEACHER=${DB_HOST_TEACHER}
      - DB_PORT_TEACHER=${DB_PORT_TEACHER}
      - DB_USER_TEACHER=${DB_USER_TEACHER}
      - DB_PASSWORD_TEACHER=${DB_PASSWORD_TEACHER}
      - DB_NAME_TEACHER=${DB_NAME_TEACHER}

  read_teachers:
    image: gabrielrv/read_teachers:latest
    container_name: read_teachers
    restart: always
    ports:
      - "8011:8011"
    environment:
      - DB_HOST_TEACHER=${DB_HOST_TEACHER}
      - DB_PORT_TEACHER=${DB_PORT_TEACHER}
      - DB_USER_TEACHER=${DB_USER_TEACHER}
      - DB_PASSWORD_TEACHER=${DB_PASSWORD_TEACHER}
      - DB_NAME_TEACHER=${DB_NAME_TEACHER}

  update_teachers:
    image: gabrielrv/update_teachers:latest
    container_name: update_teachers
    restart: always
    ports:
      - "8012:8012"
    environment:
      - DB_HOST_TEACHER=${DB_HOST_TEACHER}
      - DB_PORT_TEACHER=${DB_PORT_TEACHER}
      - DB_USER_TEACHER=${DB_USER_TEACHER}
      - DB_PASSWORD_TEACHER=${DB_PASSWORD_TEACHER}
      - DB_NAME_TEACHER=${DB_NAME_TEACHER}
