# Imagen base de Go
FROM golang:1.20

# Crear directorio de trabajo
WORKDIR /app

# Copiar archivos necesarios
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Construir el ejecutable
RUN go build -o main .

# Exponer el puerto
EXPOSE 8081

# Ejecutar la aplicación
CMD ["./main"]
