basePath: /
definitions:
  models.Material:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      subject:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: API para leer materiales desde la base de datos.
  title: Read Materials API
  version: "1.0"
paths:
  /materials:
    get:
      consumes:
      - application/json
      description: Devuelve una lista de todos los materiales almacenados en la base
        de datos.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Material'
            type: array
        "500":
          description: Error interno del servidor
          schema:
            type: string
      summary: Obtiene todos los materiales
      tags:
      - materials
swagger: "2.0"
