# Usa una imagen oficial de Node.js/Bun
FROM oven/bun:latest

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos del proyecto
COPY . .

# Instala las dependencias
RUN bun install

# Expone el puerto de la API
EXPOSE 3001

# Comando para iniciar el servicio
CMD ["bun", "run", "dev"]
