version: '3.8'

services:
  created_schedules:
    image: ${{ secrets.DOCKER_USERNAME }}/created_schedules:latest
    container_name: created_schedules
    restart: always
    env_file:
      - .env
    ports:
      - "6000:6000"
    networks:
      - schedules_network

  read_schedules:
    image: ${{ secrets.DOCKER_USERNAME }}/read_schedules:latest
    container_name: read_schedules
    restart: always
    env_file:
      - .env
    ports:
      - "6001:6001"
    networks:
      - schedules_network

  update_schedules:
    image: ${{ secrets.DOCKER_USERNAME }}/update_schedules:latest
    container_name: update_schedules
    restart: always
    env_file:
      - .env
    ports:
      - "6003:6003"
    networks:
      - schedules_network

  delete_schedules:
    image: ${{ secrets.DOCKER_USERNAME }}/delete_schedules:latest
    container_name: delete_schedules
    restart: always
    env_file:
      - .env
    ports:
      - "6002:6002"
    networks:
      - schedules_network

networks:
  schedules_network:
    driver: bridge
