version: '3.8'

services:
  created_teachers:
    image: "${DOCKER_USERNAME}/created_teachers:latest"
    container_name: created_teachers
    restart: always
    ports:
      - "8010:8010"
    env_file:
      - .env

  delete_teachers:
    image: "${DOCKER_USERNAME}/delete_teachers:latest"
    container_name: delete_teachers
    restart: always
    ports:
      - "8013:8013"
    env_file:
      - .env

  read_teachers:
    image: "${DOCKER_USERNAME}/read_teachers:latest"
    container_name: read_teachers
    restart: always
    ports:
      - "8011:8011"
    env_file:
      - .env

  update_teachers:
    image: "${DOCKER_USERNAME}/update_teachers:latest"
    container_name: update_teachers
    restart: always
    ports:
      - "8012:8012"
    env_file:
      - .env
