version: '3.8'

services:
  created_schedules:
    image: gabrielrv/created_schedules:latest
    container_name: created_schedules
    restart: always
    ports:
      - "6000:6000"
    environment:
      - DB_HOST=${DB_HOST_SCHEDULES}
      - DB_PORT=${DB_PORT_SCHEDULES}
      - DB_USER=${DB_USER_SCHEDULES}
      - DB_PASSWORD=${DB_PASSWORD_SCHEDULES}
      - DB_NAME=${DB_NAME_SCHEDULES}
    depends_on:
      - mysql_db

  delete_schedules:
    image: gabrielrv/delete_schedules:latest
    container_name: delete_schedules
    restart: always
    ports:
      - "6002:6002"
    environment:
      - DB_HOST=${DB_HOST_SCHEDULES}
      - DB_PORT=${DB_PORT_SCHEDULES}
      - DB_USER=${DB_USER_SCHEDULES}
      - DB_PASSWORD=${DB_PASSWORD_SCHEDULES}
      - DB_NAME=${DB_NAME_SCHEDULES}
    depends_on:
      - mysql_db

  read_schedules:
    image: gabrielrv/read_schedules:latest
    container_name: read_schedules
    restart: always
    ports:
      - "6001:6001"
    environment:
      - DB_HOST=${DB_HOST_SCHEDULES}
      - DB_PORT=${DB_PORT_SCHEDULES}
      - DB_USER=${DB_USER_SCHEDULES}
      - DB_PASSWORD=${DB_PASSWORD_SCHEDULES}
      - DB_NAME=${DB_NAME_SCHEDULES}
    depends_on:
      - mysql_db

  update_schedules:
    image: gabrielrv/update_schedules:latest
    container_name: update_schedules
    restart: always
    ports:
      - "6003:6003"
    environment:
      - DB_HOST=${DB_HOST_SCHEDULES}
      - DB_PORT=${DB_PORT_SCHEDULES}
      - DB_USER=${DB_USER_SCHEDULES}
      - DB_PASSWORD=${DB_PASSWORD_SCHEDULES}
      - DB_NAME=${DB_NAME_SCHEDULES}
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD_SCHEDULES}
      - MYSQL_DATABASE=${DB_NAME_SCHEDULES}
      - MYSQL_USER=${DB_USER_SCHEDULES}
      - MYSQL_PASSWORD=${DB_PASSWORD_SCHEDULES}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
