version: '3.8'

services:
  created_schedules:
    image: gabrielrv/created_schedules:latest
    container_name: created_schedules
    restart: always
    ports:
      - "6000:6000"
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./created_schedules/.env:/app/.env

  delete_schedules:
    image: gabrielrv/delete_schedules:latest
    container_name: delete_schedules
    restart: always
    ports:
      - "6002:6002"
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./delete_schedules/.env:/app/.env

  read_schedules:
    image: gabrielrv/read_schedules:latest
    container_name: read_schedules
    restart: always
    ports:
      - "6001:6001"
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./read_schedules/.env:/app/.env

  update_schedules:
    image: gabrielrv/update_schedules:latest
    container_name: update_schedules
    restart: always
    ports:
      - "6003:6003"
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./update_schedules/.env:/app/.env
