version: '3.8'

services:
  created_student_registration:
    image: ${{ secrets.DOCKER_USERNAME }}/created_student_registration:latest
    container_name: created_student_registration
    restart: always
    environment:
      - APP_PORT=8085
    ports:
      - "8085:8085"
    env_file:
      - .env
    networks:
      - student_registration_network

  delete_student_registration:
    image: ${{ secrets.DOCKER_USERNAME }}/delete_student_registration:latest
    container_name: delete_student_registration
    restart: always
    environment:
      - APP_PORT=8086
    ports:
      - "8086:8086"
    env_file:
      - .env
    networks:
      - student_registration_network

  read_student_registration:
    image: ${{ secrets.DOCKER_USERNAME }}/read_student_registration:latest
    container_name: read_student_registration
    restart: always
    environment:
      - APP_PORT=8087
    ports:
      - "8087:8087"
    env_file:
      - .env
    networks:
      - student_registration_network

  update_student_registration:
    image: ${{ secrets.DOCKER_USERNAME }}/update_student_registration:latest
    container_name: update_student_registration
    restart: always
    environment:
      - APP_PORT=8088
    ports:
      - "8088:8088"
    env_file:
      - .env
    networks:
      - student_registration_network

networks:
  student_registration_network:
    driver: bridge
