# Use official Bun image
FROM oven/bun:latest

# Set the working directory
WORKDIR /app

# Copy package files and install dependencies
COPY bun.lockb package.json ./ 

# Set environment variables
ENV NODE_ENV=production

RUN bun install

# Copy the rest of the application
COPY . .

# Expose the port (Make sure this matches the one in .env)
EXPOSE 8086

# Start the application
CMD ["bun", "run", "server.js"]
