# Usa la imagen oficial de Bun
FROM oven/bun:alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios
COPY . .

# Instala dependencias
RUN bun install

# Exponer el puerto de la appl
EXPOSE 2000

# Comando para iniciar el servicio
CMD ["bun", "run", "index.ts"]
