name: Docker Image CI/CD for Read Schedules Service

on:
  push:
    branches:
      - test
    paths:
      - 'BACKEND/schedules_management/read_schedules/**'
  pull_request:
    paths:
      - 'BACKEND/schedules_management/read_schedules/**'
    branches: ["test", "main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 📥 Paso 1: Checkout del repositorio
    - name: Checkout code
      uses: actions/checkout@v3

    # 🛠️ Paso 2: Verificar estructura del repositorio en GitHub Actions
    - name: Debug repository structure
      run: |
        echo "📂 Listando archivos en el workspace..."
        ls -R $GITHUB_WORKSPACE

    # 🔑 Paso 3: Login en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 🐳 Paso 4: Construcción de la imagen Docker
    - name: Build Docker image
      run: |
        docker build $GITHUB_WORKSPACE/BACKEND/schedules_management/read_schedules/. \
          --file $GITHUB_WORKSPACE/BACKEND/schedules_management/read_schedules/dockerfile \
          --build-arg DB_HOST=${{ secrets.DB_HOST_SCHEDULES }} \
          --build-arg DB_USER=${{ secrets.DB_USER_SCHEDULES }} \
          --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD_SCHEDULES }} \
          --build-arg DB_NAME=${{ secrets.DB_NAME_SCHEDULES }} \
          --build-arg SERVER_PORT=${{ secrets.SERVER_PORT_READ_SCHEDULES }} \
          -t ${{ secrets.DOCKER_USERNAME }}/read_schedules:latest

    # 📤 Paso 5: Subir la imagen a Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/read_schedules:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    # 📡 Paso 1: Conectar al servidor EC2 usando SSH
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.EC2_HOST_READ_SCHEDULES }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY_SCHEDULES }}
        port: 22
        script: |
          echo "🔄 Verificando y creando directorio..."
          mkdir -p ~/appSchedules/BACKEND/schedules_management/read_schedules

          echo "📝 Creando archivo .env..."
          cat <<EOF > ~/appSchedules/BACKEND/schedules_management/read_schedules/.env
          API_PORT=6001
          DB_USER=${{ secrets.DB_USER_SCHEDULES }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD_SCHEDULES }}
          DB_HOST=${{ secrets.DB_HOST_SCHEDULES }}
          DB_PORT=3306
          DB_NAME=${{ secrets.DB_NAME_SCHEDULES }}
          EOF

          echo "📦 Verificando contenido del .env..."
          cat ~/appSchedules/BACKEND/schedules_management/read_schedules/.env

          echo "🛠️ Verificando si Docker está instalado..."
          if ! command -v docker &> /dev/null; then
            echo "🔧 Instalando Docker en Amazon Linux..."
            sudo yum update -y
            sudo yum install -y docker
            sudo systemctl start docker
            sudo systemctl enable docker
            sudo usermod -aG docker ec2-user
          fi

          echo "🛑 Deteniendo y eliminando contenedor previo..."
          sudo docker stop read_schedules || true
          sudo docker rm read_schedules || true
          
          echo "⬇️ Descargando la última imagen desde Docker Hub..."
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/read_schedules:latest
          
          echo "🚀 Ejecutando el nuevo contenedor en el puerto ${{ secrets.SERVER_PORT_READ_SCHEDULES }}..."
          sudo docker run -d \
            --name read_schedules \
            -p 6001:6001 \
            --env-file ~/appSchedules/BACKEND/schedules_management/read_schedules/.env \
            ${{ secrets.DOCKER_USERNAME }}/read_schedules:latest

          echo "🔍 Verificando si el contenedor está corriendo..."
          if sudo docker ps -f name=read_schedules | grep read_schedules; then
            echo "✅ Contenedor 'read_schedules' corriendo correctamente."
          else
            echo "❌ Error al iniciar el contenedor. Revisa los logs."
            exit 1
          fi
